### PR TITLE
upgrade conjur-api-go to 0.12.4

### PR DESCRIPTION
**Pull request by karand1979**
### Desired Outcome

The desired outcome of this pull request is to upgrade to the latest version of the conjur-api-go package and any supporting dependencies. This will allow our organization to utilize the new environment variables supported by the higher version.

### Implemented Changes

We ran following commands to upgrade the version and ran the ./bin/build to ensure everything built. Also ran ./bin/test oss
go get github.com/cyberark/conjur-api-go@latest
go mod tidy

### Connected Issue/Story

Resolves #[[135](https://github.com/cyberark/terraform-provider-conjur/issues/135)]

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

### CODE REVIEW

**Comment by szh** [comment]
This is fixed in release [v0.6.9](https://github.com/cyberark/terraform-provider-conjur/releases/tag/v0.6.9) via commit https://github.com/cyberark/terraform-provider-conjur/commit/b5faaf49ccd03c4da13f1fa4fa08be5e531ab955. The main branch in this repo hasn't been updated yet but will be soon.
Thanks again for your contribution!

**Comment by karand1979** [comment]
@szh thanks! Can you let me know when it will be available in the terraform registry?

**Comment by karand1979** [comment]
@szh any updates on when main will be updated and the version updated in the Terraform registry? I noticed the .sig file is not part of the release artifacts.

**Comment by szh** [comment]
@karand1979 I'm so sorry for the delay. We're working through an internal infrastructure issue but I'm pushing for it to be done ASAP. I'll update when I know more.

**Comment by szh** [comment]
I'm glad to report that the TF registry is updated!

**Pull request closed without merging**
